# -*- coding: utf-8 -*-
"""
cleanup_gitignore.py
--------------------------------
Smart Git cleanup assistant for Guzo Guest Assist.
Scans for local, temporary, and backup files, then adds ignore rules to .gitignore automatically.
"""

import os

# Define unwanted patterns that should be ignored
IGNORE_RULES = [
    "# === AUTO-GENERATED BY cleanup_gitignore.py ===",
    "",
    "# Local scripts, automation, and backups",
    "*.bat",
    "*.log",
    "*.tmp",
    "*.bak",
    "*.lock",
    "*.csv",
    "backup/",
    "analytics/",
    "automation/",
    "storage/",
    "dashboard_backup/",
    "dashboard_clean_backup/",
    "encoding_backups/",
    "encoding_secure_report.log",
    "dashboard_encoding_report.log",
    "fix_*.py",
    "deep_clean_dashboard.py",
    "requirements_backup.txt",
    "",
    "# Environment files (keep only .env.example)",
    ".env",
    ".env.*",
    "!.env.example",
    "",
    "# Credentials and secrets",
    "credentials_*.json",
    "service_account.json",
    "guzo_service.json",
    "",
    "# Cache and compiled files",
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    ".streamlit/",
    "",
    "# System / IDE files",
    ".DS_Store",
    "Thumbs.db",
    ".vscode/",
    ".idea/",
    "",
]

def ensure_gitignore():
    gitignore_path = ".gitignore"
    if not os.path.exists(gitignore_path):
        print("❌ .gitignore not found in this directory.")
        return

    # Read existing content
    with open(gitignore_path, "r", encoding="utf-8") as f:
        existing = f.read().splitlines()

    # Append new ignore rules if missing
    added = 0
    with open(gitignore_path, "a", encoding="utf-8") as f:
        for rule in IGNORE_RULES:
            if rule.strip() and rule not in existing:
                f.write(rule + "\n")
                added += 1

    if added:
        print(f"✅ Added {added} new ignore rules to .gitignore.")
    else:
        print("ℹ️ .gitignore already up-to-date.")

if __name__ == "__main__":
    ensure_gitignore()
