# -*- coding: utf-8 -*-
"""
insert_test_booking.py – Guzo Guest Assist (Heritage & Hospitality Edition)
---------------------------------------------------------------------------
Adds a booking to Sofi Hotel Google Sheet, sends bilingual branded emails
and attaches a cultural, professional PDF confirmation slip reflecting
Ethiopian hospitality identity and international standards.
"""

import os
import argparse
from datetime import datetime
from dotenv import load_dotenv
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Attachment, FileContent, FileName, FileType, Disposition
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
import tempfile, base64

# ======================================================
# Load Environment
# ======================================================
load_dotenv(dotenv_path=os.path.join(os.getcwd(), ".env"), override=True)


# ======================================================
# PDF GENERATOR – Heritage & Hospitality Design
# ======================================================
def generate_pdf_confirmation(hotel, guest, email, phone, checkin, checkout, nights, room, revenue):
    """Generate a Guzo-branded bilingual PDF confirmation slip."""
    logo_path = os.path.join(os.getcwd(), "assets", "guzo_logo.png")
    tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    c = canvas.Canvas(tmp_file.name, pagesize=A4)
    width, height = A4

    # --- Brand Palette ---
    GUZO_BLUE = colors.HexColor("#004B8D")
    GUZO_GOLD = colors.HexColor("#FFB703")
    GUZO_GREEN = colors.HexColor("#007A33")
    GUZO_BROWN = colors.HexColor("#5C4033")
    IVORY = colors.HexColor("#FAF9F6")

    # Background
    c.setFillColor(IVORY)
    c.rect(0, 0, width, height, fill=1, stroke=0)

    # Header bar
    c.setFillColor(GUZO_BLUE)
    c.rect(0, height - 85, width, 85, fill=1, stroke=0)
    c.setFillColor(GUZO_GOLD)
    c.rect(0, height - 87, width, 3, fill=1, stroke=0)

    # Logo
    if os.path.exists(logo_path):
        c.drawImage(logo_path, 30, height - 75, width=90, height=50, mask='auto')

    # Title
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(140, height - 50, f"{hotel} Booking Confirmation")
    c.setFont("Helvetica", 10)
    c.drawString(140, height - 65, f"Generated by Guzo Guest Assist – {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    # --- Guest Information ---
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, height - 120, "Guest Information:")
    c.setFont("Helvetica", 11)
    c.drawString(60, height - 140, f"Name: {guest}")
    c.drawString(60, height - 155, f"Email: {email}")
    c.drawString(60, height - 170, f"Phone: {phone}")

    # --- Booking Details ---
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, height - 200, "Booking Details:")
    c.setFont("Helvetica", 11)
    c.drawString(60, height - 220, f"Check-in: {checkin}")
    c.drawString(60, height - 235, f"Check-out: {checkout}")
    c.drawString(60, height - 250, f"Nights: {nights}")
    c.drawString(60, height - 265, f"Room Type: {room}")
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(GUZO_BLUE)
    c.drawString(60, height - 280, f"Total: {revenue:,.2f} ETB")

    # Divider
    c.setStrokeColor(GUZO_GOLD)
    c.setLineWidth(1)
    c.line(40, height - 295, width - 40, height - 295)

    # --- Footer bilingual message ---
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(GUZO_BROWN)
    c.drawString(40, 80, "Thank you for booking with Guzo Guest Assist.")
    c.setFillColor(GUZO_GREEN)
    c.drawString(40, 65, "ጉዞዎን እንረዳለን። — Your Journey, Our Assist.")

    # Watermark
    c.saveState()
    c.setFont("Helvetica-BoldOblique", 38)
    c.setFillColorRGB(0.92, 0.92, 0.92)
    c.rotate(45)
    c.drawCentredString(420, 70, "Guzo Guest Assist Verified")
    c.restoreState()

    # Footer Details
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.grey)
    c.drawString(40, 40, f"© {datetime.now().year} Guzo Guest Assist • Addis Ababa, Ethiopia • Hospitality Technology for Africa")

    c.showPage()
    c.save()
    return tmp_file.name


# ======================================================
# GOOGLE SHEETS INSERT
# ======================================================
def insert_booking(hotel, guest, nights, checkin, checkout, room, email, phone, source, rate, remark):
    try:
        scope = [
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/drive"
        ]
        creds_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
        if not creds_path or not os.path.exists(creds_path):
            raise FileNotFoundError("Service account credentials missing.")

        creds = ServiceAccountCredentials.from_json_keyfile_name(creds_path, scope)
        client = gspread.authorize(creds)

        sheet_id = os.getenv("SOFI_HOTEL_SHEET_ID")
        if not sheet_id:
            raise ValueError("SOFI_HOTEL_SHEET_ID missing in .env")

        sheet = client.open_by_key(sheet_id).sheet1
        nights = int(nights)
        rate = float(rate)
        revenue = nights * rate

        row = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            guest, source, checkin, nights, room, rate, revenue,
            "Confirmed", "TEST-" + datetime.now().strftime("%H%M%S"),
            remark, "✅ Sent", "GuzoBot"
        ]
        sheet.append_row(row, value_input_option="USER_ENTERED")
        print(f"Booking inserted successfully for {hotel}: {guest}")
        return True, revenue
    except Exception as e:
        print("Error inserting booking:", e)
        return False, 0


# ======================================================
# EMAIL SENDER (Bilingual + Branded HTML)
# ======================================================
def send_booking_emails(hotel, guest, email, phone, checkin, checkout, nights, room, revenue, remark):
    try:
        api_key = os.getenv("SENDGRID_API_KEY")
        sender = os.getenv("SENDER_EMAIL")
        alert_recipients = os.getenv("BOOKING_ALERT_EMAIL", "")
        hotel_recipients = os.getenv("HOTEL_NOTIFICATIONS_EMAIL", "")
        all_alerts = [addr.strip() for addr in (alert_recipients + "," + hotel_recipients).split(",") if addr.strip()]

        if not api_key or not sender:
            raise ValueError("Missing SendGrid configuration in .env")

        sg = SendGridAPIClient(api_key)

        pdf_path = generate_pdf_confirmation(hotel, guest, email, phone, checkin, checkout, nights, room, revenue)
        with open(pdf_path, "rb") as f:
            encoded = base64.b64encode(f.read()).decode()

        attachment = Attachment(
            FileContent(encoded),
            FileName(f"{hotel}_Booking_{guest.replace(' ', '_')}.pdf"),
            FileType("application/pdf"),
            Disposition("attachment")
        )

        # --- Guest Email (bilingual + cultural) ---
        guest_html = f"""
        <html><body style="font-family: Arial, sans-serif; background-color:#FAF9F6; padding:20px;">
        <div style="max-width:650px; margin:auto; background:white; border-radius:10px; box-shadow:0 0 5px #ddd;">
        <div style="background-color:#004B8D; color:white; padding:20px; border-top-left-radius:10px; border-top-right-radius:10px;">
            <h2 style="margin:0;">{hotel} Booking Confirmation</h2>
        </div>
        <div style="padding:20px; color:#333;">
            <p>Dear {guest},</p>
            <p>Thank you for booking with <strong>{hotel}</strong> via <strong style='color:#004B8D;'>Guzo Guest Assist</strong>.</p>
            <p><b>Check-in:</b> {checkin}<br>
            <b>Check-out:</b> {checkout}<br>
            <b>Room:</b> {room}<br>
            <b>Total:</b> <span style="color:#004B8D;"><b>{revenue:,.2f} ETB</b></span></p>
            <hr style="border:1px solid #FFB703;">
            <h3 style="color:#004B8D;">እንኳን ደህና መጡ፣ {guest}!</h3>
            <p>መዝገብዎ ተሳክቶ ተመዝግቧል። እንኳን በደህና መጡ ወደ {hotel}።</p>
            <p style="color:#007A33;"><em>ጉዞዎን እንረዳለን። — Your Journey, Our Assist.</em></p>
            <p style="font-size:12px; color:#999;">This message was generated automatically by Guzo Guest Assist.</p>
        </div></div></body></html>
        """
        guest_msg = Mail(from_email=sender, to_emails=email,
                         subject=f"{hotel} Booking Confirmation – Guzo Guest Assist",
                         html_content=guest_html)
        guest_msg.attachment = attachment
        sg.send(guest_msg)
        print(f"Confirmation email with PDF sent to guest: {email}")

        # --- Notifications to Hotel & Internal ---
        alert_html = f"""
        <h3 style="color:#004B8D;">New Booking – {hotel}</h3>
        <p><b>Guest:</b> {guest}<br>
        <b>Email:</b> {email}<br>
        <b>Phone:</b> {phone}<br>
        <b>Check-in:</b> {checkin}<br>
        <b>Check-out:</b> {checkout}<br>
        <b>Room:</b> {room}<br>
        <b>Revenue:</b> {revenue:,.2f} ETB<br>
        <b>Remark:</b> {remark}</p>
        <p style="color:#007A33;"><em>ጉዞዎን እንረዳለን። — Your Journey, Our Assist.</em></p>
        <p style="font-size:12px; color:#777;">Logged automatically by Guzo Guest Assist.</p>
        """

        for recipient in all_alerts:
            msg = Mail(from_email=sender, to_emails=recipient,
                       subject=f"New Booking – {hotel}", html_content=alert_html)
            msg.attachment = attachment
            sg.send(msg)
            print(f"Notification email with PDF sent to: {recipient}")

        return True
    except Exception as e:
        print("Email sending error:", e)
        return False


# ======================================================
# MAIN
# ======================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Insert booking and send bilingual, branded confirmation.")
    parser.add_argument("--hotel", required=True)
    parser.add_argument("--guest", required=True)
    parser.add_argument("--nights", required=True)
    parser.add_argument("--checkin", required=True)
    parser.add_argument("--checkout", required=True)
    parser.add_argument("--room", required=True)
    parser.add_argument("--email", required=True)
    parser.add_argument("--phone", required=True)
    parser.add_argument("--source", default="Direct")
    parser.add_argument("--rate", default=0)
    parser.add_argument("--remark", default="System test booking")
    args = parser.parse_args()

    ok, revenue = insert_booking(
        args.hotel, args.guest, args.nights, args.checkin, args.checkout,
        args.room, args.email, args.phone, args.source, args.rate, args.remark
    )

    if ok:
        send_booking_emails(
            args.hotel, args.guest, args.email, args.phone, args.checkin,
            args.checkout, args.nights, args.room, revenue, args.remark
        )

    print("\nProcess complete.\n")
