# -*- coding: utf-8 -*-
"""
Daily Jobs ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ Guzo Guest Assist
-----------------------------------------------------
Automates the daily system summary, retries failed deliveries,
and logs all activities for audit and performance tracking.
"""

import os
import time
import datetime
from guzo_booking_bot.modules import (
    system_health,
    email_sender,
    telegram_sender,
)

# =======================================
#  PATHS & SETUP
# =======================================
LOG_PATH = os.path.join("logs", "daily_summary.log")
os.makedirs("logs", exist_ok=True)

# =======================================
#  UTILITIES
# =======================================
def log_message(message: str):
    """Write a timestamped message to both console and log file."""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{timestamp}] {message}"
    print(line)
    with open(LOG_PATH, "a", encoding="utf-8") as log:
        log.write(line + "\n")

# =======================================
#  RETRY WRAPPER
# =======================================
def safe_execute(action_name, func, retries=3, delay=300):
    """
    Retry a function up to `retries` times with `delay` seconds between.
    Example: safe_execute("Email Summary", send_email)
    """
    for attempt in range(1, retries + 1):
        try:
            func()
            log_message(f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ {action_name} succeeded on attempt {attempt}")
            return True
        except Exception as e:
            log_message(f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂ¸ÃÂÃÂÃÂÃÂ {action_name} failed on attempt {attempt}: {e}")
            if attempt < retries:
                log_message(f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ³ Retrying {action_name} in {delay//60} minutes...")
                time.sleep(delay)
    log_message(f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ {action_name} failed after {retries} attempts.")
    return False

# =======================================
#  MAIN DAILY SUMMARY JOB
# =======================================
def run_daily_summary():
    log_message("ÃÂÃÂÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ Starting Daily Summary...")

    # Record system health
    try:
        system_health.log_daily_summary(
            booking_sync_ok=True,
            retry_scheduler_ok=True,
            webhooks_ok=True,
            health_endpoint_ok=True,
            notes="Automated daily system check"
        )
        log_message("ÃÂÃÂÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ System health logged successfully.")
    except Exception as e:
        log_message(f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ Failed to log system health: {e}")

    today = datetime.date.today().strftime("%B %d, %Y")
    summary_message = (
        f"ÃÂÃÂÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ Guzo Daily System Summary ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ {today}\n"
        f"All key services running normally.\n\n"
        f"ÃÂÃÂÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ§ÃÂÃÂÃÂÃÂ© Modules:\n"
        f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¢ Booking Sync ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ\n"
        f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¢ Retry Scheduler ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ\n"
        f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¢ Payment Webhooks ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ\n"
        f"ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¢ Health Monitor ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ\n\n"
        f"Report auto-generated by Guzo Guest Assist automation."
    )

    # Telegram send with retries
    def send_telegram():
        telegram_sender.send_telegram_message("MANAGER_CHAT_ID", summary_message)

    # Email send with retries
    def send_email():
        email_sender.send_email(
            "manager@guzoassist.com",
            f"Guzo Daily Summary ÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ {today}",
            summary_message
        )

    # Execute with auto-retry
    safe_execute("Telegram Summary Send", send_telegram)
    safe_execute("Email Summary Send", send_email)

    log_message("ÃÂÃÂÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ Daily Summary routine completed.\n")

# =======================================
#  ENTRY POINT
# =======================================
if __name__ == "__main__":
    run_daily_summary()
